server:
  port: 8081

spring:
  application:
    name: app
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/lms?createDatabaseIfNotExist=true
    username: root
    password: root
  jackson:
    default-property-inclusion: non_empty

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka